### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by virgodi** [rubix-cube/cs207project#24]
Hi Group 7 !

I'm part of group 9 and I started implementing part 7 of the project for you. 

There are some issues with your code that I think you want to fix so that I can continue implementing:

- Your mean, std functions call self._values where you define self._value in your constructor (that's at least the case in ArrayTimeSeries)

- You also might want to add: add, sub and mum by constants

Thanks in advance !

V

**Comment by virgodi** [comment]
anyone?

**Comment by Peilin-D** [comment]
Hi Virgile, 

Thank you so much for your remind. 
They should be fixed now. 

Best,
Peilin

**Comment by Peilin-D** [comment]
Hi Virgile, the add constant functions are named addConst/subConst/multConst in SizedContainerTimeSeriesInterface.

**Comment by virgodi** [comment]
Perfect thanks Peilin !
