### ISSUE TITLE
Not so much an issue !

### ISSUE THREAD

**Issue by virgodi** [rubix-cube/cs207project#26]
Hi all !

Was wondering if you had any feedbacks on the code we provided you ? Do you need us to do anything in particular to improve it?

Let me know !

**Comment by Peilin-D** [comment]
Hi Virgile 
Thanks for your work! 
It would be fantastic if you could provide a README to tell us how to use your code and how could we test it. 
Thank you very much!

**Comment by virgodi** [comment]
Sure no problem ! I'll send a new pull request by 5pm today !

**Comment by virgodi** [comment]
Will be a bit late on that deadline sorry all !

**Comment by Peilin-D** [comment]
No problem. And for the tsbtreedb, I wonder if we should use red-black tree instead of ordinary binary tree.

**Comment by virgodi** [comment]
Ok so I've checked with Rahul and he confirmed my idea. But I also cleared some other stuff with him that I need to fix in my implementation. So it seems I won't be push before late tonight!

**Comment by Peilin-D** [comment]
Sure, thanks!

**Comment by Peilin-D** [comment]
Hi Virgile, we've changed our timeseries into a package (we added __init__.py in timeseries folder). This will affect the import. Could you make changes to the how you import timeseries?

**Comment by Peilin-D** [comment]
Also, I notice that you're using kernel corr as distance, could you use 2 * (1 - kernel_corr) ?
Thanks!

**Comment by virgodi** [comment]
Hey Peilin, adding the init.py won't make it a package. The only way not to use relative import is to make it an actual package with a set-up file. But that is not required. Also I'm not using kernel_corr but -kernel_corr so when ranking it is not affecting whether Im using 2 * (1 - kernel_corr) or -kernel_corr.

Still need me to make the changes ?

**Comment by Peilin-D** [comment]
Yes, you could still use relative import, but the current way of import should be changed. You could try re-running your tests to see if all the import work as before.
I totally understand that using -kernel_corr won't affect ranking, but to make it a well defined distance I think we'd better change it. 
Sorry for the inconvenience, thank you!

**Comment by virgodi** [comment]
ok I will change the distance tomorrow. But Im very sure adding the path is the only way to make it work. This is because I'm importing time series in a folder that is one directory up and two directories down. I checked with Rahul and he agreed with my method.

**Comment by Peilin-D** [comment]
Yes, I agree with you. I think we need to change the import in `generate_data.py`, `generate_vantagepoints.py`, `proj6script.py`, `util.py`, basically where you import `ArrayTimeSeries`. I think now we should import `timeseries.ArrayTimeSeries` to make it work, and we may also need to change the search path.

**Comment by virgodi** [comment]
ah okay I get it. I'll check it out tomorrow morning !

**Comment by Peilin-D** [comment]
Sure, thank you!
